/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:f4e62d3c-e2a6-405e-829e-3b83097275da",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_fOTBoOopn",
    "aws_user_pools_web_client_id": "n37p68951v7huffhvbkn90e0q",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://npjmeb4xdrbr5nakffc5to2ypu.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-u6aykrdtkjaznbimol2uttuy4m",
    "aws_user_files_s3_bucket": "amplifyapplocal85b9704ab2df48ab8bc1103e4efeeb1293654-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
